### PR TITLE
Update code

### PR DESCRIPTION
**Pull request by ymatsumu**
-Switched branch to updateCode, which is built on updatePseudocode (main does not reflect the change)
- Code now in python file (spectra.py)
- Added test function file (test_spectra.py)
- codeFile includes spectra_data.csv which is used for testing purposes

### CODE REVIEW

**Comment by ymatsumu** [comment]
- Completed writing all functions.
- Completed writing all test functions.
- Ready to start on documentation if everything looks fine.

**Comment by ymatsumu** [comment]
Nov. 30 commit:

- Changed readData and __init__ functions
- Created a folder for documentation
- Documentation in progress

**Comment by ymatsumu** [comment]
Dec. 4 commit:
- Documentation in progress (comments appreciated!)
- Commit without cache file

**Comment by andrewfullard** [comment]
This is looking excellent! The fitting results are really good. The only comment I have is that you don't need to use HTML in markdown documentation, but it doesn't break anything so it's okay.

**Pull request merged**
