### PR TITLE
Workflow file - homework

### PR DESCRIPTION
**Pull request by ymatsumu**
Sorry it's binary file on pr but workflow can be found from README file as well.

### CODE REVIEW

**Comment by andrewfullard** [comment]
This PR is empty

**Comment by ymatsumu** [comment]
I attached pdf, so the file was binary and it wasn't shown on PR. The workflow can be accessed from the README file!

**Comment by andrewfullard** [comment]
Okay. My feedback is that the DFD looks good, though you have a decision point which is not really something that should be in a DFD. Instead you could annotate that point with a note. I also think that identifying the Si feature by eye is unnecessary, it should be possible to try and find it computationally by e.g. fitting a Gaussian in the appropriate wavelength region and seeing if you get a result.

**Comment by ymatsumu** [comment]
I appreciate the feedback. Updated workflow is on README file!

**Pull request merged**
